# Site settings
title: Guimy
#email: your-email@domain.com
description:  Ever Tried. Ever failed. No matter. Try Again. Fail again. Fail better.
baseurl: "" # the subpath of your site, e.g. /blog/
url: guimy.tech # the base hostname & protocol for your site
twitter_username: 昵称应该怎么取才好 
github_username:  guimingyue

# Build settings
markdown: kramdown
#markdown: redcarpet
#highlighter: pygments
